### ISSUE TITLE
Cannot find protocol definition ASOBounceButtonViewDelegate ?! 

### ISSUE THREAD

**Issue by Meseery** [agusso/ASOAnimatedButton#1]
I tried a lot of tricks for this errors and they all failed, this protocol is not defined neither in example projects or even when it's installed via pod or copy ?!!

**Comment by agusso** [comment]
Have you tried to follow the guidance on 'https://github.com/agusso/ASOAnimatedButton/tree/master/Example/BounceButtonExample' and do 'pod install'?

**Comment by Meseery** [comment]
Yes of course i did it via podding and also via copy and in both cases the protocol can't be seen !

**Comment by agusso** [comment]
Hi,
Rather than I am guessing what you have done or what you have not done. It would be better if you elaborate the steps you did and sending some screenshots of your project folder will be helpful too.

**Comment by Meseery** [comment]
i just followed all the steps and imported #import "ASOBounceButtonView.h" into the file that conforms to <ASOBounceButtonViewDelegate> and found a warning and a compilation error :Undefined symbols for architecture x86_64:
  "l_OBJC_PROTOCOL_$_ASOBounceButtonViewDelegate"

Also, i tried to build BounceButtonExample project through running Example.xcworkspace and got the same error and warnings !

**Comment by agusso** [comment]
@Meseery: I still could not replicate this problem in my system. I believe you have checked your Project Target Architecture too.
