### ISSUE TITLE
iOS 6 support

### ISSUE THREAD

**Issue by lelikg** [agusso/ASOAnimatedButton#2]
Hi there, I really like this button. What do you think is the effort to adapt to iOS 6 as well?

Regards
Leon Gordin
PandaOS
http://www.panda-os.com

**Comment by agusso** [comment]
Hi Leon,

Thank you and you are welcome to fork it to adapt to iOS 6 to suit your project. However from my side, I will only support this library from iOS 7 and onwards.

Kind Regards,
Agus
