### ISSUE TITLE
Duplicate Symbols during linking

### ISSUE THREAD

**Issue by phamdacloc** [agusso/ASOAnimatedButton#3]
I've posted my questions here: https://stackoverflow.com/questions/25151454/duplicate-symbols-integrating-asoanimatedbutton

I think (not sure) there's a problem with how ASOAnimatedButton links to dependency libraries.  When enabling -all_load flag in "Other Linker Flag" under Build Settings in XCode, I get 20 duplicate symbols.

duplicate symbol _OBJC_CLASS_$_ASOTwoStateButton in:
    /Users/phamdacloc/Library/Developer/Xcode/DerivedData/HealthChron-cvyzecsyxjjbjddagxxmtcjushal/Build/Products/Debug-iphonesimulator/libPods.a(ASOTwoStateButton-B710713467C732B5.o)

**Comment by agusso** [comment]
Kindly refer to this answer http://stackoverflow.com/a/26102400
