### ISSUE TITLE
Using ASOAnimation with UIBarButtonItem

### ISSUE THREAD

**Issue by chlebta** [agusso/ASOAnimatedButton#4]
Hello, I need to Know how to use this library with UIBarButtonItem, I've tried already to create Bar button but I can't make Use ASOTwoStateButton class on it ? any solution

**Comment by agusso** [comment]
Hi there, 
Have you tried to follow its user guide in https://github.com/agusso/ASOAnimatedButton/tree/master/Example/TwoStateButtonExample

Let me know if you had already followed them and which part you stumbled.

**Comment by chlebta** [comment]
Yes I've followed the guide and as I told you I want to use bar button item
not simple button, and the problem is that in te storyboard I can't asign
ASOTwoButton class two the bar button item

On Tuesday, February 17, 2015, Agus Soedibjo notifications@github.com
wrote:

> Hi there,
> Have you tried to follow its user guide in
> https://github.com/agusso/ASOAnimatedButton/tree/master/Example/TwoStateButtonExample
> 
> Let me know if you had already followed them and which part you stumbled.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/agusso/ASOAnimatedButton/issues/4#issuecomment-74708562
> .

## 

Regards :
Kaouach Ahmed Alaeddine
Software Engineer
chlebta.com  / about.me/chlebta

**Comment by agusso** [comment]
You can't use this library for UIBarButtonItem since ASOTwoStateButton inherits from UIButton and not UIBarButtonItem.
